FROM node:4-slim

ENV SHARED_DIR /home/node-app/shared_modules
ENV APP_DIR /home/node-app/app

COPY ["finalize.sh", "link.js", "npm_install.js", "actOnModules.js", "/usr/bin/"]
RUN chmod +x /usr/bin/finalize.sh && chmod +x /usr/bin/link.js && chmod +x /usr/bin/npm_install.js && \
    mkdir /home/node-app && mkdir ${APP_DIR} &&  mkdir ${SHARED_DIR} && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 && \
    chmod +x /usr/local/bin/dumb-init

WORKDIR /home/node-app/app

ENTRYPOINT ["dumb-init"]
CMD ["npm", "start"]
