FROM node:4-slim

ENV HOME_DIR /home/node-app
ENV SHARED_DIR ${HOME_DIR}/shared_modules
ENV APP_DIR ${HOME_DIR}/app

COPY ["finalize.sh", "/usr/local/bin/"]
COPY ["link.js", "npm_install.js", "/opt/app-setup/"]
RUN (cd /opt/app-setup; npm install act-on-modules; npm install bluebird) && \
    chmod +x /usr/local/bin/finalize.sh && chmod +x /opt/app-setup/link.js && chmod +x /opt/app-setup/npm_install.js && \
    mkdir ${HOME_DIR} && mkdir ${APP_DIR} &&  mkdir ${SHARED_DIR} && \
    wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 && \
    chmod +x /usr/local/bin/dumb-init

WORKDIR ${APP_DIR}

ENTRYPOINT ["dumb-init"]
CMD ["npm", "start"]
