version: '3.5'
services:
  zookeeper-one:
    image: zookeeper:3.6
    restart: always
    hostname: zookeeper-one
    volumes:
      - "./zookeeper/one/data:/data"
      - "./zookeeper/one/datalog:/datalog"
      - "./zookeeper-conf/zoo.cfg:/conf/zoo.cfg"
    environment:
      ZOO_CONF_DIR: /conf
      ZOO_MY_ID: 1
    networks:
      - pulsar-internal
  zookeeper-two:
    image: zookeeper:3.6
    restart: always
    hostname: zookeeper-two
    volumes:
      - "./zookeeper/two/data:/data"
      - "./zookeeper/two/datalog:/datalog"
      - "./zookeeper-conf/zoo.cfg:/conf/zoo.cfg"
    environment:
      ZOO_CONF_DIR: /conf
      ZOO_MY_ID: 2
    networks:
      - pulsar-internal
  zookeeper-three:
    image: zookeeper:3.6
    restart: always
    hostname: zookeeper-three
    volumes:
      - "./zookeeper/three/data:/data"
      - "./zookeeper/three/datalog:/datalog"
      - "./zookeeper-conf/zoo.cfg:/conf/zoo.cfg"
    environment:
      ZOO_CONF_DIR: /conf
      ZOO_MY_ID: 3
    networks:
      - pulsar-internal
  bookie-one:
    image: apachepulsar/pulsar:2.5.1
    restart: always
    volumes:
      - "./bookkeeper-conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf"
      - "./bookie/one/data:/pulsar/data"
    command: ["bin/bookkeeper", "bookie"]
    networks:
      - pulsar-internal
  bookie-two:
    image: apachepulsar/pulsar:2.5.1
    restart: always
    volumes:
      - "./bookkeeper-conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf"
      - "./bookie/two/data:/pulsar/data"
    command: ["bin/bookkeeper", "bookie"]
    networks:
      - pulsar-internal
  bookie-three:
    image: apachepulsar/pulsar:2.5.1
    restart: always
    volumes:
      - "./bookkeeper-conf/bookkeeper.conf:/pulsar/conf/bookkeeper.conf"
      - "./bookie/three/data:/pulsar/data"
    command: ["bin/bookkeeper", "bookie"]
    networks:
      - pulsar-internal
  broker:
    image: apachepulsar/pulsar:2.5.1
    #Will technically be ignored with scripts in non-swarm mode, but this conveys the idea. 
    #This is cattle.
    deploy:
      replicas: 3
    restart: always
    volumes:
      - "./broker-conf/broker.conf:/pulsar/conf/broker.conf"
    command: ["bin/pulsar", "broker"]
    networks:
      - pulsar
      - pulsar-internal

networks:
  pulsar:
    name: pulsar
  pulsar-internal:
    name: pulsar-internal