FROM magnitus/node-app:6

ENV UID="1000"

COPY "app/*" ${APP_DIR}/
COPY "shared/user-store" ${SHARED_DIR}/user-store
COPY "shared/capitalize-array" ${SHARED_DIR}/capitalize-array

RUN finalize.sh

USER $UID
