FROM docker:1.11

ENV TEMPLATE_PATH /opt/build/template
ENV APP_DIR /opt/app
ENV SHARED_DIR /opt/shared

ENV SERVER_DIR /opt/server

ENV DEFAULT_SOURCE_IMAGE magnitus/node-app:4

RUN apk add --no-cache nodejs && apk add --no-cache wget

COPY ["app/", "/opt/build/"]
RUN (cd /opt/build; npm install)

COPY ["server/", "${SERVER_DIR}"]
RUN (cd ${SERVER_DIR}; npm install)

WORKDIR /opt/build

ENTRYPOINT ["/usr/bin/npm"]
CMD ["start"]

