FROM magnitus/node-app:6

ENV UID="1000"

COPY "app/*" ${APP_DIR}/
COPY "shared/module1" ${SHARED_DIR}/module1
COPY "shared/module2" ${SHARED_DIR}/module2

ENV NPM_MODULES="bluebird@3;xregexp@3.1.1"

RUN finalize.sh

USER $UID
