FROM docker:1.11

ENV TEMPLATE_PATH /opt/build/template
ENV APP_DIR /opt/app
ENV SHARED_DIR /opt/shared

RUN apk add --no-cache nodejs
COPY ["app/", "/opt/build/"]
RUN (cd /opt/build; npm install)

WORKDIR /opt/build

ENTRYPOINT ["/usr/bin/npm"]
CMD ["start"]

